version: "3.1"

services:
  graphqlblog-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
  tus:
    image: tusproject/tusd
    ports:
      - 1080:1080
